# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator

    mail_manager:
        class:     AppBundle\Manager\MailManager
        arguments: ["@mailer", "@twig"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

#    admin.activite:
#        class: AppBundle\Admin\ActiviteAdmin
#        arguments: [~, AppBundle\Entity\Activite, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Activite }